# Generated by Django 3.0.8 on 2023-05-01 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='time',
        ),
        migrations.AlterField(
            model_name='booth',
            name='college',
            field=models.CharField(choices=[('교육관', '교육관'), ('대강당', '대강당'), ('신세계관', '신세계관'), ('생활관', '생활관'), ('정문', '정문'), ('포스코관', '포스코관'), ('학문관', '학문관'), ('휴웃길', '휴웃길')], max_length=20),
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.TextField()),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='booth.Booth')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
