# Generated by Django 3.0.8 on 2023-04-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='hashtag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booth',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
