# Generated by Django 3.0.8 on 2023-04-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.IntegerField(choices=[(10, 10), (11, 11), (12, 12)], null=True),
        ),
    ]
