# Generated by Django 3.0.8 on 2023-04-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_auto_20230411_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='category',
            field=models.CharField(choices=[('음식', '음식'), ('굿즈', '굿즈'), ('체험', '체험'), ('기타', '기타')], default='음식', max_length=20),
        ),
    ]
