# Generated by Django 3.0.8 on 2023-04-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_booth_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='time',
            field=models.TextField(blank=True, default='10:00 ~ 17:00', null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.IntegerField(choices=[(10, 10), (11, 11), (12, 12)]),
        ),
    ]
