# Generated by Django 3.0.8 on 2023-04-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0004_auto_20220907_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='hashtag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
